/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                    '#2A7FFF',
        'primary-container':          '#006fee',
        'on-primary':                 '#ffffff',
        'on-primary-container':       '#fefcff',
        'primary-fixed':              '#d8e2ff',
        'secondary':                  '#006d37',
        'secondary-container':        '#6bfe9c',
        'secondary-fixed':            '#6bfe9c',
        'secondary-fixed-dim':        '#4ae183',
        'on-secondary':               '#ffffff',
        'on-secondary-container':     '#00743a',
        'on-secondary-fixed-variant': '#005228',
        'tertiary':                   '#994200',
        'tertiary-container':         '#bf5500',
        'tertiary-fixed':             '#ffdbca',
        'on-tertiary':                '#ffffff',
        'on-tertiary-fixed':          '#331100',
        'on-tertiary-fixed-variant':  '#773200',
        'error':                      '#ba1a1a',
        'error-container':            '#ffdad6',
        'on-error':                   '#ffffff',
        'on-error-container':         '#93000a',
        'surface':                    '#fbf9f8',
        'surface-bright':             '#fbf9f8',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f6f3f2',
        'surface-container':          '#f0eded',
        'surface-container-high':     '#eae8e7',
        'surface-container-highest':  '#e4e2e1',
        'on-surface':                 '#1b1c1c',
        'on-surface-variant':         '#414754',
        'outline':                    '#727786',
        'outline-variant':            '#c1c6d7',
        'background':                 '#fbf9f8',
        'on-background':              '#1b1c1c',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
